version: 1.2
workflows:
  - subclass: <CWL | WDL | NFL | GALAXY>
    primaryDescriptorPath: "/descriptor.yml"
    authors:
      - name: David Maimoun
        email: bioinfomoh@gmail.com
    topic: Fetch NM clonal complex and MenDeVAR
